[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

lib_deps =
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    bblanchon/ArduinoJson
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    mandulaj/PZEM-004T-v30
    knolleary/PubSubClient
    
build_flags =
    -DCORE_DEBUG_LEVEL=0
